version: 2.1
executors:
  node:
    docker: 
      - image: circleci/node:12.14.1

jobs:
  test_build:
    executor: node
    steps:
      - run:
          name: Test
          command: |
            npm run test
      - run:
          name: Build
          command: |
            npm run build

