version: 2.1
executors:
  node:
    docker: 
      - image: circleci/node:12.14.1

jobs:
  test:
    executor: node
    working_directory: ~/
    steps:
      - run:
          name: Test
          command: |
            npm run test
  build:
    executor: node
    working_directory: ~/
    steps:
      - run:
          name: Build
          command: |
            npm run build

workflows:
  "circleci":
    jobs:
      - test
      - build
