version: 2.1
executors:
  node:
    docker: 
      - image: circleci/node:12.14.1

jobs:
  install:
    executor: node
    steps:
      - checkout
      - run:
          name: Install
          command: |
            ls -la
            npm install
  test:
    executor: node
    steps:
      - run:
          name: Test
          command: |
            ls -la
            npm run test
  build:
    executor: node
    steps:
      - run:
          name: Build
          command: |
            npm run build

workflows:
  setup:
    jobs:
      - install
      - test:
          requires:
            - install
      - build:
          requires:
            - Install
