version: 2.1
executors:
  node:
    docker: 
      - image: circleci/node:12.14.1

jobs:
  install:
    executor: node
    steps:
      - checkout
      - restore_cache:
          key: npm-cache-v4-{{ checksum "package-lock.json" }}
      - run:
          name: Install
          command: |
            ls -la
            npm install
            cd ..
            ls -la
      - save_cache:
          key: npm-cache-v4-{{ checksum "package-lock.json" }}
          paths:
            - /home/circleci/.npm
      - persist_to_workspace:
          root: ~/
          paths:
            - .
  test:
    executor: node
    steps:
      - attach_workspace:
          at: ~/
      - run:
          name: Test
          command: |
            ls -la
            npm run test
  build:
    executor: node
    steps:
      - run:
          name: Build
          command: |
            ls -la
            npm run build

workflows:
  setup:
    jobs:
      - install
      - test:
          requires:
            - install
      - build:
          requires:
            - install
